# Generated by Django 5.1.1 on 2024-10-17 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Devedor",
            fields=[
                ("devedor_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "indice_reputacao",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("lead", models.IntegerField()),
            ],
        ),
    ]
