# Generated by Django 4.2.16 on 2024-11-05 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credor',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('PJ', 'Pessoa Jurídica'), ('PF', 'Pessoa Física')], default='PJ', max_length=2)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('razao_social', models.CharField(blank=True, max_length=255, null=True)),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('conta_id', models.AutoField(primary_key=True, serialize=False)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=30)),
                ('numero_parcelas', models.IntegerField()),
                ('credor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Devedor',
            fields=[
                ('devedor_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('PJ', 'Pessoa Jurídica'), ('PF', 'Pessoa Física')], default='PF', max_length=2)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True)),
                ('razao_social', models.CharField(blank=True, max_length=255, null=True)),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('indice_reputacao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lead', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('pagamento_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_parcela', models.IntegerField()),
                ('numero_documento', models.IntegerField()),
                ('vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('tempo_para_pagar', models.IntegerField()),
                ('valor_pagamento', models.DecimalField(decimal_places=2, max_digits=30)),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=30)),
                ('diferenca_valores', models.DecimalField(decimal_places=2, max_digits=30)),
                ('lead', models.IntegerField()),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagamentos.conta')),
                ('credor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('devedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagamentos.devedor')),
            ],
        ),
        migrations.AddField(
            model_name='conta',
            name='devedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagamentos.devedor'),
        ),
    ]
