# Generated by Django 4.2.16 on 2024-11-13 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='i_int',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Índice de interação', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='conta',
            name='i_pag',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Índice de pagamento', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='conta',
            name='i_reg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Índice de regularidade', max_digits=4, null=True),
        ),
    ]
