# Generated by Django 4.2.16 on 2024-11-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0002_conta_i_int_conta_i_pag_conta_i_reg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conta',
            name='i_pag',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Índice de pagamento atualizado', max_digits=4, null=True),
        ),
    ]
