# Generated by Django 4.2.16 on 2024-11-23 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0003_alter_conta_i_pag'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='i_rep',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Índice de reputação', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='conta',
            name='i_pag',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Índice de pagamento', max_digits=4, null=True),
        ),
    ]
