# Generated by Django 4.2.16 on 2024-11-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0004_conta_i_rep_alter_conta_i_pag'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='media_lead',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
