# Generated by Django 4.2.16 on 2024-11-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0005_conta_media_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devedor',
            name='indice_reputacao',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
