# Generated by Django 4.2.16 on 2024-11-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0006_alter_devedor_indice_reputacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devedor',
            name='indice_reputacao',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
